apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemanagement
  labels:
    app: servicemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicemanagement
  template:
    metadata:
      labels:
        app: servicemanagement
    spec:
      containers:
        - name: servicemanagement
          image: "username/servicemanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
