server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: lostphonereport
          uri: http://localhost:8082
          predicates:
            - Path=/lostPhoneReports/**, /inquiryLostReports/**
        - id: phonemanagement
          uri: http://localhost:8083
          predicates:
            - Path=/devices/**, /remoteLocks/**, /inqurySelfPhones/**
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**, 
        - id: devicerecovery
          uri: http://localhost:8085
          predicates:
            - Path=/recoveries/**, 
        - id: phonerental
          uri: http://localhost:8086
          predicates:
            - Path=/rentals/**, 
        - id: servicemanagement
          uri: http://localhost:8087
          predicates:
            - Path=/imeiBlocks/**, /usimBlocks/**, /본인기기Imei차단정보조회/**, /통신서비스차단정보조회/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: lostphonereport
          uri: http://lostphonereport:8080
          predicates:
            - Path=/lostPhoneReports/**, 
        - id: phonemanagement
          uri: http://phonemanagement:8080
          predicates:
            - Path=/devices/**, /remoteLocks/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: devicerecovery
          uri: http://devicerecovery:8080
          predicates:
            - Path=/recoveries/**, 
        - id: phonerental
          uri: http://phonerental:8080
          predicates:
            - Path=/rentals/**, 
        - id: servicemanagement
          uri: http://servicemanagement:8080
          predicates:
            - Path=/imeiBlocks/**, /usimBlocks/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
