apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostphonereport
  labels:
    app: lostphonereport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostphonereport
  template:
    metadata:
      labels:
        app: lostphonereport
    spec:
      containers:
        - name: lostphonereport
          image: "username/lostphonereport:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
