---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lostphonereport
  labels:
    app: lostphonereport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lostphonereport
  template:
    metadata:
      labels:
        app: lostphonereport
    spec:
      containers:
        - name: lostphonereport
          image: username/lostphonereport:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonemanagement
  labels:
    app: phonemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonemanagement
  template:
    metadata:
      labels:
        app: phonemanagement
    spec:
      containers:
        - name: phonemanagement
          image: username/phonemanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: username/notification:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicerecovery
  labels:
    app: devicerecovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicerecovery
  template:
    metadata:
      labels:
        app: devicerecovery
    spec:
      containers:
        - name: devicerecovery
          image: username/devicerecovery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonerental
  labels:
    app: phonerental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonerental
  template:
    metadata:
      labels:
        app: phonerental
    spec:
      containers:
        - name: phonerental
          image: username/phonerental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemanagement
  labels:
    app: servicemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicemanagement
  template:
    metadata:
      labels:
        app: servicemanagement
    spec:
      containers:
        - name: servicemanagement
          image: username/servicemanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: lostphonereport
  labels:
    app: lostphonereport
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: lostphonereport


---


apiVersion: v1
kind: Service
metadata:
  name: phonemanagement
  labels:
    app: phonemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phonemanagement


---


apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: notification


---


apiVersion: v1
kind: Service
metadata:
  name: devicerecovery
  labels:
    app: devicerecovery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: devicerecovery


---


apiVersion: v1
kind: Service
metadata:
  name: phonerental
  labels:
    app: phonerental
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: phonerental


---


apiVersion: v1
kind: Service
metadata:
  name: servicemanagement
  labels:
    app: servicemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: servicemanagement

